# Baseline 1 Configuration: Single Frame ResNet50 Classifier
# Uses only the middle frame from each video clip for group activity recognition

experiment_name: "B1_SingleFrame_ResNet50"
description: "Baseline 1: Single frame ResNet50 classifier using middle frame only"
seed: 42

# Data configuration
data:
  # Dataset paths
  dataset_root: "D:/volleyball-datasets"
  videos_path:  "D:/volleyball-datasets/videos"
  annot_path:   "D:/volleyball-datasets/annot_all.pkl"
  
  # Data splits (video IDs)
  train_split: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
  val_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  test_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  
  # Data loading parameters
  batch_size: 8
  num_workers: 4
  pin_memory: true
  shuffle_train: true
  
  # B1 specific: Single frame processing
  use_middle_frame_only: true
  sequence_length: 1
  image_size: 224
  
  # Data augmentation
  use_augmentation: true
  horizontal_flip_prob: 0.5
  use_vertical_flip: true
  vertical_flip_prob: 0.05
  color_jitter_prob: 0.9
  gaussian_blur_prob: 0.3
  gaussian_blur_kernel: 7
  sharpness_factor: 2.0
  
  # Normalization (ImageNet pretrained)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Model configuration
model:
  # Architecture
  backbone: "resnet50"
  model_type: "single_frame"
  pretrained: true
  
  # Classification
  num_classes: 8
  class_names: ["l-pass", "r-pass", "l-spike", "r_spike", "l_set", "r_set", "l_winpoint", "r_winpoint"]
  
  # B1 specific: No temporal components
  use_temporal_layer: false
  classifier_layers: [2048, 8]
  dropout: 0.5

# Training configuration
training:
  # Training parameters
  num_epochs: 10
  learning_rate: 0.0001
  weight_decay: 0.0001
  
  # Optimizer
  optimizer: "adamw"
  
  # Learning rate scheduler
  use_scheduler: true
  scheduler_type: "reduce_on_plateau"
  scheduler_patience: 3
  scheduler_factor: 0.1
  
  # Early stopping
  use_early_stopping: true
  early_stopping_patience: 5
  early_stopping_min_delta: 0.001
  
  # Mixed precision training
  use_amp: true
  
  # Device
  device: "auto"
  
  # Checkpointing
  save_best_model: true
  save_last_model: true
  checkpoint_dir: "Baseline_B1/checkpoints"
  model_name: "baseline_b1"
  
  # Logging
  log_interval: 10
  val_interval: 1

# Evaluation configuration
evaluation:
  batch_size: 32
  save_predictions: true
  save_visualizations: true
  
  # Output directories
  results_dir: "Baseline_B1/results"
  plots_dir: "Baseline_B1/results"
  
  # Visualization settings
  plot_confusion_matrix: true
  plot_class_accuracies: true
  save_classification_report: true
  
  # Figure settings
  figure_dpi: 300
  figure_format: "png"
