# Baseline 2 Configuration: Enhanced Single Frame Classifier
# Enhanced version of B1 with advanced augmentation and improved architecture

experiment_name: "B2_EnhancedSingleFrame"
description: "Baseline 2: Enhanced single frame classifier with advanced augmentation and deeper classifier"
seed: 42

# Logging and monitoring
use_tensorboard: true
use_wandb: false
wandb_project: "volleyball-activity-recognition"

# Data configuration
data:
  # Dataset paths
  dataset_root: "D:/volleyball-datasets"
  
  # Data splits (video IDs)
  train_split: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
  val_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  test_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  
  # Data loading parameters
  batch_size: 16
  num_workers: 4
  pin_memory: true
  shuffle_train: true
  
  # B2 specific: Single frame with enhanced processing
  use_middle_frame_only: true
  sequence_length: 1
  image_size: 224
  
  # Enhanced data augmentation
  use_augmentation: true
  use_advanced_augmentation: true
  horizontal_flip_prob: 0.5
  color_jitter_prob: 0.7
  gaussian_blur_prob: 0.4
  cutmix_prob: 0.3
  mixup_prob: 0.3
  
  # Additional augmentations
  random_rotation_degrees: 15
  random_perspective_prob: 0.3
  elastic_transform_prob: 0.2
  
  # Normalization (ImageNet pretrained)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Model configuration
model:
  # Architecture
  backbone: "resnet50"
  model_type: "enhanced_single_frame"
  pretrained: true
  
  # Classification
  num_classes: 8
  class_names: ["l-pass", "r-pass", "l-spike", "r_spike", "l_set", "r_set", "l_winpoint", "r_winpoint"]
  
  # B2 specific: Enhanced classifier with more layers
  use_temporal_layer: false
  classifier_layers: [2048, 1024, 512, 8]
  use_batch_norm: true
  dropout: 0.3
  
  # Additional regularization
  use_dropout_schedule: true
  label_smoothing: 0.1

# Training configuration
training:
  # Training parameters
  num_epochs: 15
  learning_rate: 0.0001
  weight_decay: 0.001
  
  # Optimizer
  optimizer: "adamw"
  
  # Learning rate scheduler
  use_scheduler: true
  scheduler_type: "cosine"
  scheduler_warmup_epochs: 3
  
  # Early stopping
  use_early_stopping: true
  early_stopping_patience: 7
  early_stopping_min_delta: 0.001
  
  # Mixed precision training
  use_amp: true
  
  # Device
  device: "auto"
  
  # Checkpointing
  save_best_model: true
  save_last_model: true
  checkpoint_dir: "Baseline_B2/checkpoints"
  model_name: "baseline_b2"
  
  # Logging
  log_interval: 10
  val_interval: 1
  
  # Advanced training techniques
  use_gradient_clipping: true
  gradient_clip_norm: 1.0

# Evaluation configuration
evaluation:
  batch_size: 32
  save_predictions: true
  save_visualizations: true
  
  # Output directories
  results_dir: "Baseline_B2/results"
  plots_dir: "Baseline_B2/plots"
  
  # Visualization settings
  plot_confusion_matrix: true
  plot_class_accuracies: true
  save_classification_report: true
  plot_training_curves: true
  
  # Figure settings
  figure_dpi: 300
  figure_format: "png"
