experiment_name: "B3_IndividualPlayerActions"
description: "Baseline 3: Individual player action recognition from cropped player regions"
seed: 42

# Logging and monitoring
use_tensorboard: true
use_wandb: false
wandb_project: "volleyball-activity-recognition"

# Data configuration
data:
  # Dataset paths
  dataset_root: "D:/volleyball-datasets"
  videos_path:  "D:/volleyball-datasets/videos"
  annot_path:   "D:/volleyball-datasets/annot_all.pkl"
  
  # Data splits (video IDs)
  train_split: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
  val_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  test_split: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]
  

  
  # Data augmentation for player crops
  use_augmentation: true
  image_size: 224
  horizontal_flip_prob: 0.5
  color_jitter_prob: 0.6
  gaussian_blur_prob: 0.3
  random_rotation_degrees: 10
  
  # Player-specific augmentations
  random_crop_scale: [0.8, 1.0]
  random_aspect_ratio: [0.9, 1.1]
  
  # Normalization (ImageNet pretrained)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Model configuration
model:
  
  person_activity:

    num_classes: 9
    class_names: ["waiting", "setting", "digging", "falling", "spiking", "blocking", "jumping", "moving", "standing"]
    

    # Data loading parameters
    batch_size: 128
    num_workers: 4
    pin_memory: True
    shuffle_train: true
  
  group_activity:

    num_classes: 8
    class_names: ["l-pass", "r-pass", "l-spike", "r_spike", "l_set", "r_set", "l_winpoint", "r_winpoint"]
    

    # Data loading parameters
    batch_size: 32
    num_workers: 4
    pin_memory: True
    shuffle_train: true

# Training configuration
training:
  person_activity:
    # Training parameters
    num_epochs: 10
    learning_rate: 0.0001
    
    # Optimizer
    optimizer: "adamW"
    
    # Learning rate scheduler
    use_scheduler: true
    scheduler_type: "reduce_on_plateau"
    scheduler_patience: 3
    scheduler_factor: 0.1
    
    # Mixed precision training
    use_amp: true
    
    # Device
    device: "auto"
    
    # Checkpointing
    save_best_model: true
    save_last_model: true
    checkpoint_dir: "Baseline_B3/B3_A/checkpoints"
    model_name: "best_volleyball_b3_model.pth"

  group_activity:
    # Training parameters
    num_epochs: 25
    learning_rate: 0.0001
    weight_decay: 1
    
    # Optimizer
    optimizer: "adamW"
    
    # Learning rate scheduler
    use_scheduler: true
    scheduler_type: "ReduceLROnPlateau"
    scheduler_patience: 5
    scheduler_factor: 0.1
    
    # Mixed precision training
    use_amp: true
    
    # Device
    device: "auto"
    
    # Checkpointing
    save_best_model: true
    save_last_model: False
    checkpoint_dir: "Baseline_B3/B3_B/checkpoints"
    model_name: "best_volleyball_model (2).pth"

  

# Evaluation configuration
evaluation:
  batch_size: 32
  save_predictions: true
  save_visualizations: true
  
  # Output directories
  results_dir: "Baseline_B3/B3_B/resulates"
  plots_dir: "Baseline_B3/B3_B/resulates"
  
  # Visualization settings
  plot_confusion_matrix: true
  plot_class_accuracies: true
  save_classification_report: true
  plot_per_player_analysis: true
  
  
  # Figure settings
  figure_dpi: 300
  figure_format: "png"
