experiment_name: "B5 model"
description: ""
seed: 42


# Data configuration
data:
  # Dataset paths
  dataset_root: "D:/volleyball-datasets"
  videos_path:  "D:/volleyball-datasets/videos"
  annot_path:   "D:/volleyball-datasets/annot_all.pkl"
  
  # Data splits (video IDs)
  train_split: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
  val_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  test_split: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  

  
  # Data augmentation for player crops
  use_augmentation: true
  image_size: 224
  horizontal_flip_prob: 0.5
  color_jitter_prob: 0.6
  gaussian_blur_prob: 0.3
  random_rotation_degrees: 10
  
  # Player-specific augmentations
  random_crop_scale: [0.8, 1.0]
  random_aspect_ratio: [0.9, 1.1]
  
  # Normalization (ImageNet pretrained)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Model configuration
model:
  
  person_activity:

    num_classes: 9
    class_names: ["waiting", "setting", "digging", "falling", "spiking", "blocking", "jumping", "moving", "standing"]
    
    # Hyper parameter
    hidden_size: 512
    num_layers: 1

    # Data loading parameters
    batch_size: 2
    num_workers: 0
    pin_memory: false
    shuffle_train: true
  
  group_activity:

    num_classes: 8
    class_names: ["l-pass", "r-pass", "l-spike", "r_spike", "l_set", "r_set", "l_winpoint", "r_winpoint"]
    
    # Hyper parameter
    hidden_size: 512
    num_layers: 1

    # Data loading parameters
    batch_size: 8
    num_workers: 2
    pin_memory: false
    shuffle_train: true

# Training configuration
training:
  person_activity:
    # Training parameters
    num_epochs: 20
    learning_rate: 0.00001
    weight_decay: 0.1
    label_smoothing : 0.02
    
    # Optimizer
    optimizer: "adamW"
    
    # Learning rate scheduler
    use_scheduler: true
    scheduler_type: "reduce_on_plateau"
    scheduler_patience: 2
    scheduler_factor: 0.1
    
    # Mixed precision training
    use_amp: true
    
    # Device
    device: "auto"
    
    # Resume training from checkpoint
    resume_from_checkpoint: True
    checkpoint_path: "/kaggle/input/best-b8-model-at-epoch23/pytorch/default/1/checkpoint_epoch_20.pth"


    # Checkpointing
    save_best_model: true
    save_last_model: true
    checkpoint_dir: "Baseline_B5/checkpoints"
    model_name: "best_Baseline_B5_A_model"

  group_activity:
    # Training parameters
    num_epochs: 25
    learning_rate: 0.001
    weight_decay: 1
    
    # Optimizer
    optimizer: "adamW"
    
    # Learning rate scheduler
    use_scheduler: true
    scheduler_type: "ReduceLROnPlateau"
    scheduler_patience: 2
    scheduler_factor: 0.1
    
    # Mixed precision training
    use_amp: true
    
    # Device
    device: "auto"
    
    # Checkpointing
    save_best_model: true
    save_last_model: False
    checkpoint_dir: "Baseline_B5/checkpoints"
    model_name: "best_Baseline_B5_B_model"

  

# Evaluation configuration
evaluation:
  batch_size: 8
  save_predictions: true
  save_visualizations: true
  
  # Output directories
  results_dir: "Baseline_B5/results"
  plots_dir: "Baseline_B5/results"
  
  # Visualization settings
  plot_confusion_matrix: true
  plot_class_accuracies: true
  save_classification_report: true
  plot_per_player_analysis: true
  
  
  # Figure settings
  figure_dpi: 300
  figure_format: "png"
